version: 2

aliases:
  - &setup_miniconda
    name: setup_miniconda
    command: |
       mkdir -p workspace
       git clone -b validateNightlyNew git@github.com:CDAT/cdat workspace/cdat
       python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'

  - &conda_rerender
    name: conda_rerender
    command: |
       git clone https://github.com/CDAT/conda-recipes.git $WORKDIR/conda-recipes 
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       BUILD_SCRIPT="$WORKDIR/conda-recipes/build_tools/conda_build.py"
       python $BUILD_SCRIPT -w $WORKDIR -l $LAST_STABLE -B 0 -p $PKG_NAME -b $CIRCLE_BRANCH --do_rerender

  - &conda_build
    name: conda_build
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       conda config --add channels conda-forge --force
       conda config --add channels cdat/label/nightly --force
       conda config --set channel_priority strict
       BUILD_SCRIPT="$WORKDIR/conda-recipes/build_tools/conda_build.py"
       python $BUILD_SCRIPT -w $WORKDIR -p $PKG_NAME --build_version $BUILD_VARIANT_VER --do_build

  - &setup_run_tests
    name: setup_run_tests
    environment:
       # PKGS: "cdms2 cdat_info udunits2 testsrunner matplotlib numpy genutil vtk-cdat cdutil vcs 'proj4<5' mesalib"
       # Note that installing vcs can be problematic here because vcs depends on dv3d
       # 
       PKGS: "testsrunner genutil cdutil vcs"
       CHANNELS: "-c cdat/label/nightly -c conda-forge"
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       if [[ `uname` == "Linux" ]]; then
          MESA="mesalib=18.3.1"
       else
          MESA="mesalib=17.3.9"
       fi
       echo "conda create -y -n $ENV_NAME --use-local $CHANNELS \"$CONDA_PY_VER\" $PKG_NAME $MESA $PKGS $COVERAGE_PKGS \"$LIBNETCDF\""
       conda create -y -n $ENV_NAME --use-local $CHANNELS "$CONDA_PY_VER" $PKG_NAME $MESA $PKGS $COVERAGE_PKGS "$LIBNETCDF"
       conda activate $ENV_NAME
       conda list

  - &get_testdata
    name: get_testdata
    command: | 
      git clone git://github.com/cdat/uvcdat-testdata

  - &run_tests
    name: run_tests
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate $ENV_NAME
       python run_tests.py -H -v2 -n 2 $COVERAGE
       conda deactivate

  - &conda_upload
    name: conda_upload
    command: |
       if [[ $CIRCLE_BRANCH != "master" ]]; then
          exit 0
       fi
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       UPLOAD_OPTIONS="-t $CONDA_UPLOAD_TOKEN upload -u $USER -l $LABEL"
       anaconda $UPLOAD_OPTIONS $WORKDIR/miniconda/conda-bld/noarch/$PKG_NAME-$VERSION.`date +%Y*`0.tar.bz2 --force

  - &run_coveralls
    name: run_coveralls
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate $ENV_NAME
       coveralls
       conda deactivate

jobs:
   #
   # setup_miniconda, rerender and build -- 'cdutil' is noarch
   #
   macos_setup:
      macos:
         xcode: "11.4.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "dv3d"
         REPO_NAME: "dv3d"
         LAST_STABLE: "8.2"
         BUILD_VARIANT_VER: "noarch"
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *conda_rerender
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths: 
                 - macos_build

   linux_setup:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "dv3d"
         REPO_NAME: "dv3d"
         LAST_STABLE: "8.2"
         BUILD_VARIANT_VER: "noarch"
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *conda_rerender
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build

   #
   # run tests with libnetcdf nompi
   #
   macos_dv3d_nompi_py36:
      macos:
         xcode: "11.4.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "dv3d"
         REPO_NAME: "dv3d"
         ENV_NAME: "test_dv3d"
         CONDA_PY_VER: "python>=3.6,<3.7"
         LIBNETCDF: "libnetcdf=*=nompi_*"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *setup_run_tests
         - run: *get_testdata
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png

   macos_dv3d_nompi_py37:
      macos:
         xcode: "11.4.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "dv3d"
         REPO_NAME: "dv3d"
         ENV_NAME: "test_dv3d"
         CONDA_PY_VER: "python>=3.7,<3.8"
         LIBNETCDF: "libnetcdf=*=nompi_*"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *setup_run_tests
         - run: *get_testdata
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png

   macos_dv3d_nompi_py38:
      macos:
         xcode: "11.4.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "dv3d"
         REPO_NAME: "dv3d"
         ENV_NAME: "test_dv3d"
         CONDA_PY_VER: "python>=3.8,<3.9"
         LIBNETCDF: "libnetcdf=*=nompi_*"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *setup_run_tests
         - run: *get_testdata
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png

   linux_dv3d_nompi_py36:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "dv3d"
         REPO_NAME: "dv3d"
         ENV_NAME: "test_dv3d"
         CONDA_PY_VER: "python>=3.6,<3.7"
         LIBNETCDF: "libnetcdf=*=nompi_*"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *setup_run_tests
         - run: *get_testdata
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png

   linux_dv3d_nompi_py37:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "dv3d"
         REPO_NAME: "dv3d"
         ENV_NAME: "test_dv3d"
         CONDA_PY_VER: "python>=3.7,<3.8"
         LIBNETCDF: "libnetcdf=*=nompi_*"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *setup_run_tests
         - run: *get_testdata
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png

   linux_dv3d_nompi_py38:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "dv3d"
         REPO_NAME: "dv3d"
         ENV_NAME: "test_dv3d"
         CONDA_PY_VER: "python>=3.8,<3.9"
         #COVERAGE: "-c tests/coverage.json --coverage-from-repo"
         #COVERAGE_PKGS: "coverage coveralls"
         LIBNETCDF: "libnetcdf=*=nompi_*"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *setup_run_tests
         - run: *get_testdata
         - run: *run_tests
         #- run: *run_coveralls
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png

   #
   # run tests with libnetcdf mpich
   #
   macos_dv3d_mpich_py36:
      macos:
         xcode: "11.4.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "dv3d"
         REPO_NAME: "dv3d"
         ENV_NAME: "test_dv3d"
         CONDA_PY_VER: "python>=3.6,<3.7"
         LIBNETCDF: "libnetcdf=*=mpi_mpich_*"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *setup_run_tests
         - run: *get_testdata
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png

   macos_dv3d_mpich_py37:
      macos:
         xcode: "11.4.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "dv3d"
         REPO_NAME: "dv3d"
         ENV_NAME: "test_dv3d"
         CONDA_PY_VER: "python>=3.7,<3.8"
         LIBNETCDF: "libnetcdf=*=mpi_mpich_*"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *setup_run_tests
         - run: *get_testdata
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png

   macos_dv3d_mpich_py38:
      macos:
         xcode: "11.4.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "dv3d"
         REPO_NAME: "dv3d"
         ENV_NAME: "test_dv3d"
         CONDA_PY_VER: "python>=3.8,<3.9"
         LIBNETCDF: "libnetcdf=*=mpi_mpich_*"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *setup_run_tests
         - run: *get_testdata
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png

   linux_dv3d_mpich_py36:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "dv3d"
         REPO_NAME: "dv3d"
         ENV_NAME: "test_dv3d"
         CONDA_PY_VER: "python>=3.6,<3.7"
         LIBNETCDF: "libnetcdf=*=mpi_mpich_*"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *setup_run_tests
         - run: *get_testdata
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png

   linux_dv3d_mpich_py37:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "dv3d"
         REPO_NAME: "dv3d"
         ENV_NAME: "test_dv3d"
         CONDA_PY_VER: "python>=3.7,<3.8"
         LIBNETCDF: "libnetcdf=*=mpi_mpich_*"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *setup_run_tests
         - run: *get_testdata
         - run: *run_tests
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png

   linux_dv3d_mpich_py38:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "dv3d"
         REPO_NAME: "dv3d"
         ENV_NAME: "test_dv3d"
         CONDA_PY_VER: "python>=3.8,<3.9"
         #COVERAGE: "-c tests/coverage.json --coverage-from-repo"
         #COVERAGE_PKGS: "coverage coveralls"
         LIBNETCDF: "libnetcdf=*=mpi_mpich_*"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *setup_run_tests
         - run: *get_testdata
         - run: *run_tests
         #- run: *run_coveralls
         - store_artifacts:
              path: tests_html
              destination: tests_html
         - store_artifacts:
             path: tests_png
             destination: tests_png

   upload:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "dv3d"
         VERSION: "8.2"
         USER: "cdat"
         LABEL: "nightly"
      steps:
         - attach_workspace:
              at: .
         - run: pwd
         - run: *conda_upload

workflows:
   version: 2
   dv3d:
      jobs:
         - macos_setup
         - linux_setup
         - macos_dv3d_mpich_py36:
              requires:
                 - macos_setup
         - macos_dv3d_mpich_py37:
              requires:
                 - macos_setup
         - macos_dv3d_mpich_py38:
              requires:
                 - macos_setup
         - linux_dv3d_mpich_py36:
              requires:
                 - linux_setup
         - linux_dv3d_mpich_py37:
              requires:
                 - linux_setup
         - linux_dv3d_mpich_py38:
              requires:
                 - linux_setup

         - macos_dv3d_nompi_py36:
              requires:
                 - macos_setup
         - macos_dv3d_nompi_py37:
              requires:
                 - macos_setup
         - macos_dv3d_nompi_py38:
              requires:
                 - macos_setup
         - linux_dv3d_nompi_py36:
              requires:
                 - linux_setup
         - linux_dv3d_nompi_py37:
              requires:
                 - linux_setup
         - linux_dv3d_nompi_py38:
              requires:
                 - linux_setup

         - upload:
              requires:
                 - macos_dv3d_mpich_py36
                 - macos_dv3d_mpich_py37
                 - macos_dv3d_mpich_py38
                 - linux_dv3d_mpich_py36
                 - linux_dv3d_mpich_py37
                 - linux_dv3d_mpich_py38

                 - macos_dv3d_nompi_py36
                 - macos_dv3d_nompi_py37
                 - macos_dv3d_nompi_py38
                 - linux_dv3d_nompi_py36
                 - linux_dv3d_nompi_py37
                 - linux_dv3d_nompi_py38
